function [ ] = ShowLaserScan( scan )
%
% ShowLaserScan( scan )
%
% Plots all the laser points from a single scan in cartesian space.
%
% INPUTS:
%   scan: struct containing a single laser scan, as generated by
%           GetLaserScans
%
% SEE ALSO:
%   GetLaserScans
%

% Geoff Pascoe
% February 2015
% Mobile Robotics Group, Oxford University.

% verify inputs
if (~(isempty(scan) || ...
        (isstruct(scan) && ...
        (all(isfield(scan, {'timestamp', 'ranges', 'reflectances'}))))))
    error(['%s - scan must be a struct output from ' ...
        'GetLaserScans().'], mfilename);
end

if ~isempty(scan)
    
    % project polar to cartesian
    angles = -((0:size(scan.ranges, 1)-1).'*-scan.step_size - scan.start_angle + 90) * pi/180;
    coords = [scan.ranges.*cos(angles) scan.ranges.*sin(angles)];
    
    % plot cartesian scans
    colormap jet;
    %whitebg(gcf,'black');
    scatter(coords(:,1), coords(:,2), 10, scan.reflectances, 'filled');
    axis([-1 1 -1 1])
    axis ij
    axis square
    caxis([0 1000])
    title(num2str(int64(scan.timestamp)));
    xlabel('x [m]');
    ylabel('y [m]');
    
else
    warning('%s - scan is empty.', mfilename);
end

end